name: dietary_app
description: 私人饮食助理

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.1.2
  fl_chart: ^0.67.0
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: LXGWWenKai
      fonts:
        - asset: assets/fonts/LXGWWenKai-Regular.ttf
